// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY02QYXCLiJLTtLD0uFpW9WshsLnrNEHk',
    appId: '1:133722923116:web:8bed246d7e7c90350c7849',
    messagingSenderId: '133722923116',
    projectId: 'house-rental-app-c34dd',
    authDomain: 'house-rental-app-c34dd.firebaseapp.com',
    storageBucket: 'house-rental-app-c34dd.firebasestorage.app',
    measurementId: 'G-Z98ZXDHR7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcLHP8cQwmXxbUfMCh-idsj656oH9EtI',
    appId: '1:133722923116:android:141592b9242e53de0c7849',
    messagingSenderId: '133722923116',
    projectId: 'house-rental-app-c34dd',
    storageBucket: 'house-rental-app-c34dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2fDtLBisQctCMJZ6AGCHo-Slf4jZvAK0',
    appId: '1:133722923116:ios:9e8b35fa3d5e027d0c7849',
    messagingSenderId: '133722923116',
    projectId: 'house-rental-app-c34dd',
    storageBucket: 'house-rental-app-c34dd.firebasestorage.app',
    iosBundleId: 'com.example.houseRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2fDtLBisQctCMJZ6AGCHo-Slf4jZvAK0',
    appId: '1:133722923116:ios:9e8b35fa3d5e027d0c7849',
    messagingSenderId: '133722923116',
    projectId: 'house-rental-app-c34dd',
    storageBucket: 'house-rental-app-c34dd.firebasestorage.app',
    iosBundleId: 'com.example.houseRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY02QYXCLiJLTtLD0uFpW9WshsLnrNEHk',
    appId: '1:133722923116:web:b3536d1eae192eaa0c7849',
    messagingSenderId: '133722923116',
    projectId: 'house-rental-app-c34dd',
    authDomain: 'house-rental-app-c34dd.firebaseapp.com',
    storageBucket: 'house-rental-app-c34dd.firebasestorage.app',
    measurementId: 'G-TSQFBS40SH',
  );
}
